name: whiteboard_sdk_flutter
description: A Flutter wrapper for netless whiteboard sdk
version: 0.1.0
author: netless-io
homepage: https://github.com/netless-io/Whiteboard-Flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_inappwebview: ^4.0.0+4
  webview_flutter:
    git:
      url: https://gitee.com/liuhong1happy/webview_flutter
      ref: a747cd4
  
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: